<a href="https://colab.research.google.com/github/whcnblue/2022-ai/blob/main/ex01_220413.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
print ("x:\n", x)

x:
 [[1 2 3]
 [4 5 6]]


# 대각선 원소는 1이고 나머지는 0인 2차원 NumPy 배열을 만듦.

$ x = ax $

In [7]:
from scipy import sparse

# 대각선 원소는 1이고 나머지는 0인 2차원 NumPy 배열을 만듦.
eye = np.eye(4)
print ("Numpy 배열:\n", eye)

Numpy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# NumPy 배열을 CSR 포맷의 SciPy 희소 행렬로 변환
# 0이 아닌 원소만 저장됨
# (참고) CSR: Compressed sparse row. 행의 인덱스를 압축하여 저장
sparse_matrix = sparse.csr_matrix(eye)
print ("Scipy의 CSR 행렬: \n", sparse_matrix)

Scipy의 CSR 행렬: 
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [10]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print ("COO 표현:\n", eye_coo)

COO 표현:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [11]:
from numpy.lib.polynomial import polyfit
imprort matplotlib.pyplot as polyfit

# -10에서 10까지 100개의 간격으로 나뉘어진 배열을 생성
x = np.linspace(-10, 10, 100)
# sin 함수를 사용하여 y배열을 생성
y = np.sin(x)
# plot 함수는 한 배열의 값을 다른 배열에 대응해서 선 그래프를 그림
plt.plot(x, y, marker='x')
plt.show()

SyntaxError: ignored